name: Publish PowerShell Module to Gallery

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Module to PowerShell Gallery
        shell: pwsh
        run: |
          Publish-Module -Path ./F5-LTM -NuGetApiKey "${{ env.POWERSHELLGALLERY_APIKEY }}" -Force
