#
# Module manifest for module 'F5-LTM'
#
# Generated by: Joel Newton
#
# Generated on: 5/22/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'F5-LTM.psm1'

# Version number of this module.
ModuleVersion = '1.3.0'

# ID used to uniquely identify this module
GUID = 'f4649254-d64a-407d-822f-66a4618ed5fb'

# Author of this module
Author = 'Joel Newton'

# Company or vendor of this module
CompanyName = 'SpringCM'

# Copyright statement for this module
Copyright = '(c) 2016 Joel Newton. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module uses the REST API in the F5 LTM v11.6 to query and manipulate the F5 LTM device.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = ''

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = ''

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'PSModule','F5','LTM','REST','API'

        # A URL to the license for this module.
        #LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/joel74/POSH-LTM-Rest'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

