 name: Publish Module to PowerShell Gallery
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.POWERSHELLGALLERY_APIKEY }}
